name: "update-release-links"

on:
  workflow_run:
    workflows:
      - "publish-windows-x64"
      - "publish-windows-arm"
      - "publish-ubuntu-x64"
      - "publish-ubuntu-arm"
      - "publish-macos-x64"
      - "publish-macos-arm"
    types:
      - completed

jobs:
  update-release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Set environment variables
        run: |
          echo "VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_ENV
          echo "NAME=$(node -p "require('./package.json').name")" >> $GITHUB_ENV

      - name: Wait for all assets
        uses: actions/github-script@v6
        with:
          script: |
            const maxAttempts = 20;
            const delaySeconds = 30;
            const expectedAssets = [
              '-windows-x64.msi',
              '-windows-arm.msi',
              '-ubuntu-x64.deb',
              '-ubuntu-arm.deb',
              '-macos-x64.dmg',
              '-macos-arm.dmg'
            ];
            
            for (let attempt = 1; attempt <= maxAttempts; attempt++) {
              try {
                const release = await github.rest.repos.getReleaseByTag({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  tag: `v${process.env.VERSION}`
                });
                
                const assets = release.data.assets.map(a => a.name);
                const missingAssets = expectedAssets.filter(ext => 
                  !assets.some(a => a.endsWith(ext))
                );
                
                if (missingAssets.length === 0) {
                  console.log('All assets found!');
                  break;
                }
                
                console.log(`Missing assets: ${missingAssets.join(', ')}`);
                if (attempt === maxAttempts) {
                  throw new Error(`Timed out waiting for assets: ${missingAssets.join(', ')}`);
                }
                
                console.log(`Attempt ${attempt}, waiting ${delaySeconds} seconds...`);
                await new Promise(r => setTimeout(r, delaySeconds * 1000));
              } catch (error) {
                if (attempt === maxAttempts) {
                  throw error;
                }
                console.log(`Attempt ${attempt} failed, waiting ${delaySeconds} seconds...`);
                await new Promise(r => setTimeout(r, delaySeconds * 1000));
              }
            }

      - name: Update release body
        uses: actions/github-script@v6
        with:
          script: |
            const release = await github.rest.repos.getReleaseByTag({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag: `v${process.env.VERSION}`
            });
            
            const newBody = `## Supa Bass-O-Matic v${process.env.VERSION}

            ### Downloads
            - Windows (x64): [${process.env.NAME}-${process.env.VERSION}-windows-x64.msi](https://github.com/${context.repo.owner}/${context.repo.repo}/releases/download/v${process.env.VERSION}/${process.env.NAME}-${process.env.VERSION}-windows-x64.msi)
            - Windows (ARM): [${process.env.NAME}-${process.env.VERSION}-windows-arm.msi](https://github.com/${context.repo.owner}/${context.repo.repo}/releases/download/v${process.env.VERSION}/${process.env.NAME}-${process.env.VERSION}-windows-arm.msi)
            - Ubuntu (x64): [${process.env.NAME}-${process.env.VERSION}-ubuntu-x64.deb](https://github.com/${context.repo.owner}/${context.repo.repo}/releases/download/v${process.env.VERSION}/${process.env.NAME}-${process.env.VERSION}-ubuntu-x64.deb)
            - Ubuntu (ARM): [${process.env.NAME}-${process.env.VERSION}-ubuntu-arm.deb](https://github.com/${context.repo.owner}/${context.repo.repo}/releases/download/v${process.env.VERSION}/${process.env.NAME}-${process.env.VERSION}-ubuntu-arm.deb)
            - macOS (x64): [${process.env.NAME}-${process.env.VERSION}-macos-x64.dmg](https://github.com/${context.repo.owner}/${context.repo.repo}/releases/download/v${process.env.VERSION}/${process.env.NAME}-${process.env.VERSION}-macos-x64.dmg)
            - macOS (ARM): [${process.env.NAME}-${process.env.VERSION}-macos-arm.dmg](https://github.com/${context.repo.owner}/${context.repo.repo}/releases/download/v${process.env.VERSION}/${process.env.NAME}-${process.env.VERSION}-macos-arm.dmg)`;
            
            await github.rest.repos.updateRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              release_id: release.data.id,
              body: newBody
            });
